[project]
name = "uv-python-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "autopep8>=2.3.2",
    "black>=25.9.0",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
]
